version: "3.9"

networks:
  urlshortner_network:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapping host port 3000 to container port 3000
    depends_on:
      - mongo
    networks:
      - urlshortner_network
    environment:
      - MONGO_URI=mongodb://mongo:27017/urlShortener # Use environment variables for MongoDB connection
      - NODE_ENV=production # Set the Node environment

  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Mapping host port 5000 to container port 80
    depends_on:
      - backend
    networks:
      - urlshortner_network

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017" # Exposing MongoDB port
    volumes:
      - mongo_data:/data/db
    networks:
      - urlshortner_network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin # Optional MongoDB authentication
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongo_data:
