# Frontend Dockerfile
FROM nginx:alpine

# Copy static files to the Nginx container
COPY . /usr/share/nginx/html

# Expose port 80 for the frontend
EXPOSE 80

# Use default Nginx command
CMD ["nginx", "-g", "daemon off;"]
